### PR TITLE
Update RCASD for June PresCat Update

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui Please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 Can you check the output on the RCASD file? Most of the addresses were not actually making it through the geocoder.

If you look through the log, there is an error about the "Array Subscript out of range". This is being caused because typos in the source files. I fixed one by creating a new file in the L drive and adding edit to the file name. If you could do that for the rest of the errors as the come up. Let me know if you have questions.

**Comment by mcohenui** [comment]
@Woliver01 an example of what was occurring. One address was labeled as 330-3304. So the program was producing an address for every number between 330 and 3304. Which was causing an error and the program to shut down in the middle of geocoding.

**Comment by Woliver01** [comment]
@mcohenui Thanks, Mychal. That's the only one I see (the Feb 24-29 one). I'm not recognizing other areas where there are issues. In the it "invalid argument" statements?

**Comment by mcohenui** [comment]
@Woliver01 When I run it I am getting an error for 1331-13313 Alabama Avenue Southeast. On the May 4-8 file. Are you note getting that error?

**Comment by Woliver01** [comment]
@mcohenui So I see the error but it doesn't tell me which file has the error. Also, it seems like I'm only getting one error at a time, is your log showing multiple errors? By this I mean, only once I added the edited Feb 24-29 to the rcasd program was I able to see the 1331-13313 Alabama error.

**Comment by mcohenui** [comment]
@woliver01 yes, the program stops running anytime it encounters an error.

**Comment by mcohenui** [comment]
The program itself is good to merge once you  deal with the array errors

**Comment by Woliver01** [comment]
@mcohenui I guess what I'm saying is that I'll have to go through each csv to see which one has the address that is causing the error because the log doesn't tell me. And then beyond that, because it only shows me one error at a time, I won't have a good sense how many addresses have this error.

**Comment by Woliver01** [comment]
@mcohenui Either way, I went through each one and it ran it with no errors so I'll continue with the merge. I may add this to the notes as a potential step, unless you have a more efficient work around.

**Pull request merged**
