### PR TITLE
October DCHD update

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui there was an error with the 9-14 csv and 8-03 csv. There was a variabel that the program couldn't read. Please review.

### CODE REVIEW

**Comment by mcohenui** [comment]
@ptatian Hey Peter, retagging you on this for review. It looks like DHCD added a new category to its RCASD notices. I changed the format to include the new category, but was unsure of how to test it, given that the format.sas file is pulled directly from the L drive.

cc @Woliver01

**Comment by mcohenui** [comment]
@Woliver01 Ok Will, this should be good to merge. Please closely review the output from the batch submit to make sure the changes to the formatting are good to go.

**Comment by Woliver01** [comment]
@mcohenui ok, will do.

**Comment by Woliver01** [comment]
@mcohenui no errors on log.

**Pull request merged**
