### PR TITLE
Update Rcasd_2020.sas

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui There was an "Invalid input" notice for some of the spreadsheets. I checked the datasets and they look fine to me, particularly because the number of records read in are accurate. There was also an error saying "Array subscript out of range." I haven't encountered that before so I'm not sure how to go about fixing that.

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 The array subscript error is due to the a typo in the addresses. Basically the array function gives you each number within a range (1-5 Example ave becomes 1,2,3,4,5 Example ave). In this instance, the out of range error refers to the number of returns being over a certain limit. If you look at the address causing the error it is something like 300-3000 example ave. So the array is causing an error, rather than generating over 2000 returns. Try googling the address, you may be able to ascertain which property is actually in the notice and fix the typo. Otherwise, you may need to create a new version of the raw file to exclude that address.

**Comment by Woliver01** [comment]
@mcohenui So I don't actually think the issue is the range in these cases. I think an issue could potentially be that some of the addresses/units are listed as #N313 or something like that, with a letter and then a number and the program may not be able to read letters after a number sign. Another issue might be the addresses listed as NE rather than Northeast, or vice versa. The last thing that might be it would be some sort of confusion with the # of units and the sale price values. 

I could go through and Google each address but, since there are over 200 addresses, that would be very time consuming. If that's the only way, I could use some assistance, maybe we could split up the spreadsheets?

**Comment by mcohenui** [comment]
@Woliver01 Huh. I am not getting the error you are referring to. Only the one associated with 330 Pennsylvania Ave. Can you send me your log?

**Comment by mcohenui** [comment]
@Woliver01 good to merge

**Pull request merged**
