### PR TITLE
Update Rcasd 2020

### PR DESCRIPTION
**Pull request by Woliver01**
@mcohenui Hey Mychal, I didn't get any errors but there seems to be some issues with the counts for a handful of the notices. Also when I look in the library after I've run the code, the notices after September aren't showing up. Could you take a look?

### CODE REVIEW

**Comment by mcohenui** [comment]
@Woliver01 can you say more about what you are seeing? I see an issue with only the most recent file. Which it looks like is caused by the raw file having the wrong format. I am not seeing any issue with the other files after September. When you say they are not showing up in the library, do you mean they aren't showing up in the Work.RCASD_2020 table?

**Comment by mcohenui** [comment]
@Woliver01 Also, if it is easier to discuss over a call or zoom, let me know. I have a meeting at 4 but otherwise free.

**Comment by Woliver01** [comment]
@mcohenui So I was seeing a few of the csv's coming back with a warning that said that the count was wrong, specifically 12/28-1/1, 10/12-10/16, 10/5-10/9, 9/28-10/2. And I just got out of a meeting but could I give you a call now before your meeting at 4?

**Comment by mcohenui** [comment]
@Woliver01 So if there are some irregularities in how the file is structured, the count generated by the code can be off. An easy way to check if it is actually missing notices, is to go to the raw file and count how many notices are included.

**Pull request merged**
